pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                sh 'docker build -t "jenkins-test" .'
            }
        }
        stage('Test') {
            steps {
                sh 'docker run --rm jenkins-test'
            }

        }
    }
}
