# Server Configuration
server.port=8081
server.servlet.context-path=/api

# Application Name
spring.application.name=leap-backend

# Logging
logging.level.root=INFO
logging.level.com.neueda.leap=DEBUG

# Jackson Configuration
spring.jackson.serialization.indent-output=true
spring.jackson.default-property-inclusion=non_null
